#!/usr/bin/env node
/**
 * Version consistency checker.
 *
 * bytepad has two independent version streams:
 *
 *   1. The app itself - sourced from the root package.json `version` field.
 *   2. The docker/mcp-server subproject - sourced from its own
 *      package.json `version` field. It is a deliberately separate build
 *      graph (its own express 4 vs the app's express 5, its own Docker
 *      build context - see the "Typecheck (container MCP server)" step in
 *      .github/workflows/ci.yml) and packaged Electron builds don't even
 *      ship it, so it is versioned independently rather than forced to
 *      track the app.
 *
 * Everywhere else that mentions either version is a *copy*, not a source.
 * This script re-derives each copy's expected value from the two sources
 * above and fails if any copy has drifted. This is the guard the project
 * was missing: `public/sw.js` sat two releases stale at 0.23.2 (which
 * mattered - CACHE_NAME derives from it, so cache rotation silently didn't
 * happen), and docker/mcp-server/Dockerfile's LABEL survived an entire
 * release still reading the previous version. A `grep` someone remembers
 * to run by hand is exactly the check that was believed to already be
 * passing both times.
 *
 * package-lock.json (both the root one and docker/mcp-server's) is
 * deliberately not checked: it's regenerated by
 * `npm install --package-lock-only`, not hand-edited, so treating it as a
 * manual location would just be re-checking npm's own output.
 *
 * Run: node scripts/check-version.js  (wired up as `npm run check:version`)
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const read = (relPath) => readFileSync(join(ROOT, relPath), 'utf8');

const appPkg = JSON.parse(read('package.json'));
const mcpPkg = JSON.parse(read('docker/mcp-server/package.json'));

const APP_VERSION = appPkg.version;
const MCP_VERSION = mcpPkg.version;
// SECURITY.md's supported-versions table wants a minor *series* ("0.25.x"),
// not an exact patch - it names the whole line of releases that's supported,
// not one build. See the check for that file below.
const APP_SERIES = `${APP_VERSION.split('.').slice(0, 2).join('.')}.x`;

function check(file, regex, expected, describe) {
  const content = read(file);
  const match = content.match(regex);
  if (!match) {
    return { file, describe, ok: false, found: null, expected, reason: 'pattern not found - file structure may have changed' };
  }
  return { file, describe, ok: match[1] === expected, found: match[1], expected };
}

// StatusBar.tsx / SettingsPanel.tsx render the version from live state
// (src/utils/appVersion.ts) rather than a literal - `bytepad v{appVersion}`
// passes unconditionally, since there's nothing to drift. If either ever
// regresses back to a hardcoded literal, this falls through to comparing
// that literal against APP_VERSION like any other tracked location.
function checkLiveOrLiteral(file, liveNeedle, literalRegex, expected, describe) {
  const content = read(file);
  if (content.includes(liveNeedle)) {
    return { file, describe, ok: true, found: '(live, via src/utils/appVersion.ts)', expected };
  }
  const match = content.match(literalRegex);
  if (!match) {
    return { file, describe, ok: false, found: null, expected, reason: 'pattern not found - file structure may have changed' };
  }
  return { file, describe, ok: match[1] === expected, found: match[1], expected };
}

const checks = [
  // ---- app version (source: package.json) ----
  check('README.md', /badge\/version-([\w.]+)-green/, APP_VERSION, 'version badge'),
  check('public/sw.js', /const APP_VERSION = '([\d.]+)'/, APP_VERSION, 'service worker cache-busting version'),
  checkLiveOrLiteral('src/components/layout/StatusBar.tsx', 'bytepad v{appVersion}', /bytepad v([\d.]+)/, APP_VERSION, 'status bar footer'),
  checkLiveOrLiteral('src/components/common/SettingsPanel.tsx', 'bytepad v{appVersion}', /bytepad v([\d.]+)/, APP_VERSION, 'settings modal footer'),
  check('docs/VERSION_LOCATIONS.md', /Son güncelleme: v([\d.]+)/, APP_VERSION, 'doc footer'),
  check('SECURITY.md', /\| ([\d.]+\.x) \(latest\) \|/, APP_SERIES, 'supported versions table'),

  // ---- docker/mcp-server version (source: docker/mcp-server/package.json) ----
  check('docker/mcp-server/Dockerfile', /LABEL version="([\d.]+)"/, MCP_VERSION, 'Dockerfile LABEL'),
  check('docker/mcp-server/src/routes.ts', /version: '([\d.]+)'/, MCP_VERSION, 'health route response'),
  check('docker/mcp-server/src/server.ts', /name: 'bytepad', version: '([\d.]+)'/, MCP_VERSION, 'MCP server info (createMCPServer)'),
  check('docker/mcp-server/src/server.ts', /npm_package_version \|\| '([\d.]+)'/, MCP_VERSION, 'health endpoint fallback'),
  check('docker-compose.yml', /image: bytepad\/mcp-server:([\d.]+)/, MCP_VERSION, 'docker-compose image tag'),
  check('README.md', /image: bytepad\/mcp-server:([\d.]+)/, MCP_VERSION, 'docker-compose usage snippet'),
  check('electron/services/dockerService.ts', /const IMAGE_TAG = '([\d.]+)'/, MCP_VERSION, 'Electron docker image tag'),
];

// ---- report ----
const line = '-'.repeat(60);
console.log(line);
console.log('Version consistency check');
console.log(line);
console.log(`App version (package.json):                ${APP_VERSION}`);
console.log(`docker/mcp-server version (its package.json): ${MCP_VERSION}`);
console.log('');

const failures = checks.filter((c) => !c.ok);

for (const c of checks) {
  const status = c.ok ? 'OK  ' : 'FAIL';
  const detail = c.ok ? '' : `  expected "${c.expected}", found ${c.found === null ? c.reason : `"${c.found}"`}`;
  console.log(`[${status}] ${c.file} — ${c.describe}${detail}`);
}

console.log(line);

if (failures.length > 0) {
  console.log(`FAIL: ${failures.length} location(s) drifted from their source of truth (see above).`);
  process.exitCode = 1;
} else {
  console.log(`OK: all ${checks.length} tracked locations match their source of truth.`);
}
